# Generated by Django 5.2 on 2025-04-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('CONFERENCE', 'Conference'), ('WORKSHOP', 'Workshop'), ('WEBINAR', 'Webinar'), ('MEETUP', 'Meetup'), ('CONCERT', 'Concert'), ('FESTIVAL', 'Festival'), ('SPORTS', 'Sports'), ('CHARITY', 'Charity'), ('BUSINESS', 'Business'), ('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding')], default='CONFERENCE', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=250)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('events', models.ManyToManyField(related_name='Participants', to='event_app.event')),
            ],
        ),
    ]
