# Generated by Django 5.2 on 2025-11-08 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('CONFERENCE', 'Conference'), ('WORKSHOP', 'Workshop'), ('WEBINAR', 'Webinar'), ('MEETUP', 'Meetup'), ('CONCERT', 'Concert'), ('FESTIVAL', 'Festival'), ('SPORTS', 'Sports'), ('CHARITY', 'Charity'), ('BUSINESS', 'Business'), ('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding')], default='CONFERENCE', max_length=100)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=250)),
                ('category', models.ManyToManyField(related_name='events', to='event_app.category')),
                ('participants', models.ManyToManyField(related_name='participant_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_asset/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_app.event')),
            ],
        ),
    ]
