# Generated by Django 5.2 on 2025-04-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_description',
        ),
    ]
